[tool.black]
line-length = 79
[tool.mypy]
strict="yes"
[tool.pylint.'FORMAT']
expected-line-ending-format="LF"
max-line-length=79
[tool.pylint.'LOGGING']
logging-format-style="new"
[tool.pylint.'MESSAGES CONTROL']
confidence=""
[tool.pylint.'REPORTS']
output-format="colorized"
reports="no"
[tool.pylint.'STRING']
check-quote-consistency="yes"
check-str-concat-over-line-jumps="yes"
